---
title: "chain_report"
format:
  pdf:
    fig-width: 9
    fig-height: 6
editor: source
editor_options: 
  chunk_output_type: console
params:
  model_data_file: runs/hanam_ak_1/model_data.hdf5
  chain_file: runs/hanam_ak_1/chain_prior_50_uncorrected.parquet
---

## Simulation study MCMC fit

```{r}
library(targets)
library(tidyverse)
suppressMessages(tar_source())

model_data <- read_model_data(params$model_data_file)

chain <- read_chain(params$chain_file)
```

```{r}

sample_dates <- model_data$observations %>%
  distinct(ix_subject, year_observed)

strains_observed <- model_data$observations %>%
  distinct(ix_subject, strain_year)

ggplot() +
  
  geom_rect(aes(xmin = -Inf, xmax = year_of_birth - 0.5, ymin = ix_subject - 0.5, ymax = ix_subject + 0.5),
            fill = "grey90",
            model_data$subject_birth_data) +
  
  geom_tile(aes(x = year, y = ix_subject),
            fill = "lightblue",
            model_data$infections) +
  
  geom_point(aes(x = year_observed, y = ix_subject),
             size = 0.5,
             sample_dates) +
  
  geom_hline(aes(yintercept = ix_subject + 0.5), sample_dates %>% distinct(ix_subject),
             colour = "grey40") +
  
  geom_rug(aes(x = year), tibble(year = model_data$modelled_years)) +
  
  theme_bw()

ggplot() +
  
  geom_rect(aes(xmin = -Inf, xmax = year_of_birth - 0.5, ymin = ix_subject - 0.5, ymax = ix_subject + 0.5),
            fill = "grey90",
            model_data$subject_birth_data) +
  
  geom_tile(aes(x = year, y = ix_subject),
            fill = "lightblue",
            model_data$infections)  +
  
  geom_tile(aes(x = strain_year, y = ix_subject),
             fill = "red", alpha = 0.3,
             strains_observed) +
  geom_point(aes(x = year_observed, y = ix_subject),
             size = 0.5,
             sample_dates) +
  
  geom_hline(aes(yintercept = ix_subject + 0.5), sample_dates %>% distinct(ix_subject),
             colour = "white") +
  
  geom_rug(aes(x = year), tibble(year = model_data$modelled_years)) +
  
  theme_bw()
```

```{r}

true_values <- tribble(
  ~name, ~value,
  "mu_long", 2.0,
  # "mu_sum", 2.0 + 2.0,
  "mu_short", 2.0,
  "sigma_long", 0.15,
  "sigma_short", 0.05,
  "tau", 0.05,
  "omega", 0.75,
  "obs_sd", 1.5
)



# chain <- chain %>%
#   mutate(mu_short = mu_sum - mu_long)

warmup_steps <- 1500

parnames <- colnames(chain)[5:11]

chain_filt <- chain %>%
  filter(.iteration > warmup_steps)

chain_filt_wide <- chain_filt %>% 
  select(.iteration, .chain, any_of(parnames)) %>%
  pivot_longer(any_of(parnames))

```

```{r}

chain %>%
  select(.iteration, .chain, any_of(parnames)) %>%
  pivot_longer(any_of(parnames)) %>%
  ggplot() +
  geom_line(aes(x = .iteration, y = value, colour = factor(.chain))) +
  
  geom_vline(xintercept = warmup_steps) +
  
  geom_hline(aes(yintercept = value), true_values) +
  
  facet_wrap(~name, scales = "free_y")

ggplot() +
  geom_line(aes(x = .iteration, y = value, colour = factor(.chain)),
            chain_filt_wide) +
  
  geom_hline(aes(yintercept = value), true_values) +
  
  facet_wrap(~name, scales = "free_y")

ggplot() +
  geom_histogram(aes(x = value), bins = 50,
                 chain_filt_wide) +
  
  geom_vline(aes(xintercept = value), true_values) +
  
  facet_wrap(~name, scales = "free")


mcmc_pairs(chain_filt, pars = colnames(chain)[5:9])

```

```{r}


strains_observed <- model_data$observations %>%
  distinct(ix_subject, ix_strain)

plot_data_inf <- get_inf_data(chain_filt, model_data)

ggplot() +
  geom_tile(aes(x = ix_t, y = ix_subject, fill = p),
            plot_data_inf)  +
  
  scale_fill_viridis_c(option = "B") +
  
  geom_point(aes(x = ix_t, y = ix_subject), model_data$infections, size = 1.0, colour = "white") +
  geom_point(aes(x = ix_t, y = ix_subject), model_data$infections, size = 0.5, stroke = 0.5, colour = "black") +
  
  geom_hline(aes(yintercept = ix_subject + 0.5), sample_dates %>% distinct(ix_subject),
             linewidth = 0.2,
             colour = "white")


autoplot(precrec::evalmod(scores = plot_data_inf$p, labels = plot_data_inf$inf), curvetype = "ROC")




plot_data_inf_count <- get_inf_count(chain, model_data)


ggplot() +
  geom_line(aes(x = .iteration, y = total_inf, colour = factor(.chain)),
            plot_data_inf_count) +
  
  geom_vline(xintercept = warmup_steps) +

  geom_hline(yintercept = nrow(model_data$infections)) +
  
  coord_cartesian(ylim = c(0, NA))


```
